name: 'Allure Launch'
description: 'Launches Allure TestOps job'
inputs:
  allure-token:
    description: 'ALLURE_TOKEN'
    required: true
  cron:
    description: 'Is this a cron check?'
    default: 'false'
runs:
  using: "composite"
  steps:
  - name: Launch Allure TestOps
    run: bundle exec fastlane allure_launch cron:${{ inputs.cron }}
    shell: bash
    env:
      ALLURE_TOKEN: ${{ inputs.allure-token }}
      GITHUB_EVENT: ${{ toJson(github.event) }}
