/*
 * Copyright (c) 2014-2026 Stream.io Inc. All rights reserved.
 *
 * Licensed under the Stream License;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://github.com/GetStream/stream-chat-android/blob/main/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.getstream.chat.android.compose.sample.feature.poc.uploadcontext

/**
 * PoC: exposing the message id to a custom `FileUploader` at upload time.
 *
 * Simulates an app that uploads attachments to its own CDN and needs to link each uploaded file to the
 * message that will contain it. The message keeps the id generated by the SDK; the app backend simply
 * receives that id together with the upload (see [LinkingFileUploader]), so no id rewriting is needed
 * anywhere in the pipeline.
 */
object UploadContextPoc {

    /**
     * Toggles the whole PoC on/off. Off by default because [LinkingFileUploader] does not perform real
     * uploads; flip to true to try the flow and watch the [TAG] logs.
     */
    const val ENABLED = false

    const val TAG = "UploadContextPoc"
}
