package io.getstream.chat.android.ui.message.list.adapter

internal val FULL_ATTACHMENT_ITEM_PAYLOAD_DIFF: AttachmentItemPayloadDiff = AttachmentItemPayloadDiff(
    authorName = true,
    authorLink = true,
    titleLink = true,
    thumbUrl = true,
    imageUrl = true,
    assetUrl = true,
    ogUrl = true,
    mimeType = true,
    fileSize = true,
    title = true,
    text = true,
    type = true,
    image = true,
    url = true,
    name = true,
    upload = true,
    uploadState = true,
)
internal val EMPTY_ATTACHMENT_ITEM_PAYLOAD_DIFF = AttachmentItemPayloadDiff(
    authorName = false,
    authorLink = false,
    titleLink = false,
    thumbUrl = false,
    imageUrl = false,
    assetUrl = false,
    ogUrl = false,
    mimeType = false,
    fileSize = false,
    title = false,
    text = false,
    type = false,
    image = false,
    url = false,
    name = false,
    upload = false,
    uploadState = false,
)
