name: 'Setup Java'
description: 'Setup Java'
runs:
  using: "composite"
  steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 17
