/*
 * Copyright (c) 2014-2026 Stream.io Inc. All rights reserved.
 *
 * Licensed under the Stream License;
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    https://github.com/GetStream/stream-chat-android/blob/main/LICENSE
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.getstream.chat.android.ai.compose.sample.domain

import io.getstream.chat.android.models.Message

/**
 * Checks if the message is generated by an AI.
 *
 * The agent must set `ai_generated` on the message when it is created; that flag is the
 * contract. The user-id prefix is only a fallback for a backend that does not set it, and
 * matches the id the reference agents build (`ai-bot-<channelId>`).
 */
internal fun Message.isFromAi(): Boolean =
    extraData["ai_generated"] == true || user.id.startsWith("ai-bot-")
