name: App Distribute CI v7

# Temporary workflow to publish the v7 sample as a separate app in Firebase. When v7 is released in
# production, we can remove this workflow and update the main `app-distribute.yml` instead

on:
  push:
    branches:
      - v7
  workflow_dispatch:
jobs:
  build_compose_sample_app:
    permissions:
      contents: read
      contents: read
    name: Build and Distribute Compose Sample App
    runs-on: ubuntu-24.04
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: Prepare environment
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
          RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}
        run: |
          git fetch --unshallow
          echo "${{ env.RELEASE_KEYSTORE }}" > .sign/release.keystore.asc
          gpg -d --passphrase "${{ env.PASSPHRASE }}" --batch .sign/release.keystore.asc > .sign/release.keystore
          echo "${{ env.RELEASE_KEYSTORE_PROPERTIES }}" > .sign/keystore.properties.asc
          gpg -d --passphrase "${{ env.PASSPHRASE }}" --batch .sign/keystore.properties.asc > .sign/keystore.properties
      - name: Assemble
        run: ./gradlew :stream-chat-android-compose-sample:assembleRelease --stacktrace
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.1
        with:
          appId: "1:17048947178:android:07dc1e8e56b65c1f40ca93" # V7 demo app id
          serviceCredentialsFileContent: ${{ secrets.STREAM_ANDROID_FIREBASE_CREDENTIALS_APP_CONTENT }}
          groups: stream-testers
          file: stream-chat-android-compose-sample/build/outputs/apk/demo/release/stream-chat-android-compose-sample-demo-release.apk
