name: Build and test

on:
  push:
    branches:
      - develop
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  debug_build:
    permissions:
      actions: write
      contents: read
    name: Debug build
    runs-on: ubuntu-22.04
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0.0.0
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: Build
        run: ./gradlew assembleDebug
  release_build:
    permissions:
      actions: write
      contents: read
    name: Release build
    runs-on: ubuntu-22.04
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0.0.0
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: Build
        run: ./gradlew assembleRelease
  tests:
    permissions:
      actions: write
      contents: read
    name: Tests
    runs-on: ubuntu-22.04
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0.0.0
        with:
          fetch-depth: 0 # fetch all history for sonar analysis
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: Unit tests
        run: ./gradlew :testCoverage
      - name: Upload test results
        uses: actions/upload-artifact@v7.0.1
        if: failure()
        with:
          name: testResults
          path: ./**/build/reports/tests/**
      - uses: GetStream/android-ci-actions/actions/setup-ruby@main
      - name: Sonar
        run: bundle exec fastlane run_sonar_analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  size_check_xml:
    permissions:
      actions: write
      contents: read
    name: Size Check XML
    runs-on: ubuntu-22.04
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0.0.0
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: build demo debug
        run: ./gradlew stream-chat-android-ui-components-sample:assembleDemoDebug
      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.2.2
        with:
          artifact_path: ./stream-chat-android-ui-components-sample/build/outputs/apk/demo/debug/stream-chat-android-ui-components-sample-demo-debug.apk
          emerge_api_key: ${{ secrets.EMERGE_TOOLS_API_KEY }}
          build_type: debug
  size_check_compose:
    permissions:
      actions: write
      contents: read
    name: Size Check Compose
    runs-on: ubuntu-22.04
      contents: read
      pull-requests: read
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0.0.0
      - uses: GetStream/android-ci-actions/actions/setup-java@cb46e4f44d105a68738bfd2a1cfd156bb768665b
      - name: build debug
        run: ./gradlew stream-chat-android-compose-sample:assembleDebug
      - name: Upload artifact to Emerge
        uses: EmergeTools/emerge-upload-action@v1.2.2
        with:
          artifact_path: ./stream-chat-android-compose-sample/build/outputs/apk/demo/debug/stream-chat-android-compose-sample-demo-debug.apk
          emerge_api_key: ${{ secrets.EMERGE_TOOLS_API_KEY }}
          build_type: debug
