name: docusaurus

on:
  push:
    branches:
      - main # default branch name for each repo that docs should be push from
    paths:
      - docusaurus/**
jobs:
  push_docusaurus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
