name: docusaurus

on:
  push:
    branches:
      - main # default branch name for each repo that docs should be push from
  workflow_dispatch:
jobs:
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
