name: Pull request CI checks

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  base-android-ci:
    permissions:
      contents: read
      pull-requests: read
    uses: GetStream/stream-build-conventions-android/.github/workflows/android-ci.yml@8c5fbade4ee9c06a0a979bcb0866e64669254f73
    secrets:
      BUILD_CACHE_AWS_REGION: ${{ secrets.BUILD_CACHE_AWS_REGION }}
      BUILD_CACHE_AWS_BUCKET: ${{ secrets.BUILD_CACHE_AWS_BUCKET }}
      BUILD_CACHE_AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_CACHE_AWS_ACCESS_KEY_ID }}
      BUILD_CACHE_AWS_SECRET_KEY: ${{ secrets.BUILD_CACHE_AWS_SECRET_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  detekt:
    permissions:
      contents: read
      pull-requests: read
    name: Detekt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: GetStream/stream-build-conventions-android/.github/actions/setup-gradle@v0.13.1
      - name: Detekt
        run: ./gradlew detekt
  rubocop:
    permissions:
      contents: read
      pull-requests: read
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: GetStream/android-ci-actions/actions/setup-ruby@main
      - run: bundle exec fastlane rubocop
