name: Publish API Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    uses: GetStream/stream-build-conventions-android/.github/workflows/publish-api-docs.yml@f1696693da135081bbb836470332ac5396aedfe9
    permissions:
      contents: write
    secrets:
      slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_ANDROID_CICD }}
