name: ReleaseDocs

on:
  push:
    branches:
      - main

jobs:
  publish_dokka:
    name: Dokka docs
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: main
      - uses: ./.github/actions/setup-java
      - name: Generate Dokka HTML docs
        run: ./gradlew dokkaHtmlMultimodule
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.STREAM_PUBLIC_BOT_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule
          publish_branch: gh-pages
