name: ReleaseDocs

on:
  push:
    branches:
      - main

jobs:
  publish_dokka:
    name: Dokka docs
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - name: Generate Dokka HTML docs
        run: ./gradlew dokkaHtmlMultimodule
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.STREAM_PUBLIC_BOT_TOKEN }}
          publish_dir: ./build/dokka/htmlMultiModule
          publish_branch: gh-pages
  push_docusaurus:
    name: Publish docusaurus docs
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0
        with:
          ref: main
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          distribution: adopt
          java-version: 17
      - name: push
        uses: GetStream/push-stream-chat-docusaurus-action@main
        with:
          target-branch: 'production'
        env:
          DOCUSAURUS_GH_TOKEN: ${{ secrets.DOCUSAURUS_GH_TOKEN }}
