name: SquashRelease

on:
  workflow_run:
    workflows: ["Publish"]
    types:
      - completed

jobs:
  release_to_main:
    name: Sync main with release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps: 
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: release
          fetch-depth: 0
      - name: Create squashed branch
        run: | 
          git fetch
          git checkout -b release-squash
          git reset $(git merge-base origin/develop $(git rev-parse --abbrev-ref HEAD))
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:        
          add: '.'
          message: "Release squashed commits"
          default_author: github_actions
          push: false
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.STREAM_PUBLIC_BOT_TOKEN }}
          branch: release-squash
          force: true
  