name: VersionBump

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
          with:
            ref: develop
      - name: Bump version
        run: ./gradlew version-bump
      - name: Commit changes
        run: | 
          git add buildSrc/src/main/kotlin/io/getstream/chat/android/Configuration.kt
          git commit -m "AUTOMATION: version bump"
