name: Stream Chat Android Offline CI

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: KtLint
      run: bash ./gradlew :stream-chat-android-offline:ktlintCheck
    - name: Unit tests
      run: bash ./gradlew :stream-chat-android-offline:test --stacktrace
    - name: Coverage
      run: ./gradlew :stream-chat-android-offline:jacocoTestReport
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
    - name: Upload testDebugUnitTest Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: testDebugUnitTest
        path: stream-chat-android-offline/build/reports/tests/testDebugUnitTest
    - name: Upload testDebugUnitTest Results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: testReleaseUnitTest
        path: stream-chat-android-offline/build/reports/tests/testReleaseUnitTest

