name: Stream Chat Android Client CI

on: [push, pull_request]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: ktlint
        run: ./gradlew :stream-chat-android-client:ktlintCheck :stream-chat-android-client-sample:ktlintCheck
      - name: Unit tests
        run: ./gradlew :stream-chat-android-client:test :stream-chat-android-client-sample:test --stacktrace
      - name: Coverage
        run: ./gradlew :stream-chat-android-client:jacocoTestReport
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
      - name: Upload testDebugUnitTest results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testDebugUnitTest
          path: stream-chat-android-client/build/reports/tests/testDebugUnitTest
      - name: Upload testDebugUnitTest results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testReleaseUnitTest
          path: stream-chat-android-client/build/reports/tests/testReleaseUnitTest
